export const TeamData = [
    {
        img: "/images/team/1.png",
        name: "Charlotte Verhout",
        role: "Therapeut",
        uni: "Universiteit van Amsterdam",
        clints: "245 cliënten",
        rating: "4.7",
        content: "Carlette is een professionele therapeut met meer dan 15 jaar ervaring in het veld. Ze heeft een brede kennis van verschillende therapeutische technieken en benaderingen, variërend van cognitieve gedragstherapie tot mindfulness. Door de jaren heen heeft ze met een divers cliëntenbestand gewerkt, waaronder individuen die kampen met angst, depressie, en relatieproblemen.",
    },
    {
        img: "/images/team/2.png",
        name: "Kevin Jansen",
        role: "Psycholoog",
        uni: "Rijksuniversiteit Groningen",
        clints: "183  cliënten",
        rating: "4.5",
        content: "Kevin Jansen therapePsycholoog ut met meer dan 15 jaar ervaring in het veld. Ze heeft een brede kennis van verschillende therapeutische technieken en benaderingen, variërend van cognitieve gedragstherapie tot mindfulness. Door de jaren heen heeft ze met een divers cliëntenbestand gewerkt",
    },
    {
        img: "/images/team/3.png",
        name: "Mike Chang",
        role: "Therapeut",
        uni: "Universiteit Utrech",
        clints: "148  cliënten",
        rating: "4.9",
        content: "Carlette is een professionele therapeut met meer dan 15 jaar ervaring in het veld. Ze heeft een brede kennis van verschillende therapeutische technieken en benaderingen, variërend van cognitieve gedragstherapie tot mindfulness. Door de jaren heen heeft ze met een divers cliëntenbestand gewerkt, waaronder individuen die kampen met angst, depressie, en relatieproblemen.",
    },
    {
        img: "/images/team/4.png",
        name: "Deborah Klaassen",
        role: "Therapeut",
        uni: "Universiteit Leiden",
        clints: "126 cliënten",
        rating: "4.8",
        content: "Carlette is een professionele therapeut met meer dan 15 jaar ervaring in het veld. Ze heeft een brede kennis van verschillende therapeutische technieken en benaderingen, variërend van cognitieve gedragstherapie tot mindfulness. Door de jaren heen heeft ze met een divers cliëntenbestand gewerkt, waaronder individuen die kampen met angst, depressie, en relatieproblemen.",
    },
    {
        img: "/images/team/5.png",
        name: "Enti Debrink",
        role: "Therapeut",
        uni: "Universiteit Leiden",
        clints: "116 cliënten",
        rating: "4.9",
        content: "Carlette is een professionele therapeut met meer dan 15 jaar ervaring in het veld. Ze heeft een brede kennis van verschillende therapeutische technieken en benaderingen, variërend van cognitieve gedragstherapie tot mindfulness. Door de jaren heen heeft ze met een divers cliëntenbestand gewerkt, waaronder individuen die kampen met angst, depressie, en relatieproblemen.",
    },
    {
        img: "/images/team/6.png",
        name: "Mustafi Antera",
        role: "Therapeut",
        uni: " Universiteit van Amsterdam",
        clints: "22 cliënten",
        rating: "4.4",
        content: "Carlette is een professionele therapeut met meer dan 15 jaar ervaring in het veld. Ze heeft een brede kennis van verschillende therapeutische technieken en benaderingen, variërend van cognitieve gedragstherapie tot mindfulness. Door de jaren heen heeft ze met een divers cliëntenbestand gewerkt, waaronder individuen die kampen met angst, depressie, en relatieproblemen.",
    },
    {
        img: "/images/team/7.png",
        name: "Pieter Vreding",
        role: "Therapeut",
        uni: "Rijksuniversiteit Groningen",
        clints: "97 cliënten",
        rating: "5.0",
        content: "Carlette is een professionele therapeut met meer dan 15 jaar ervaring in het veld. Ze heeft een brede kennis van verschillende therapeutische technieken en benaderingen, variërend van cognitieve gedragstherapie tot mindfulness. Door de jaren heen heeft ze met een divers cliëntenbestand gewerkt, waaronder individuen die kampen met angst, depressie, en relatieproblemen.",
    },
    {
        img: "/images/team/8.png",
        name: "Samantha Divé",
        role: "Therapeut",
        uni: "Erasmus Universiteit Rotterdam",
        clints: "85 cliënten",
        rating: "4.6",
        content: "Carlette is een professionele therapeut met meer dan 15 jaar ervaring in het veld. Ze heeft een brede kennis van verschillende therapeutische technieken en benaderingen, variërend van cognitieve gedragstherapie tot mindfulness. Door de jaren heen heeft ze met een divers cliëntenbestand gewerkt, waaronder individuen die kampen met angst, depressie, en relatieproblemen.",
    },
]